### ISSUE TITLE
Unable to get player IP when bungee proxy

### ISSUE THREAD

**Issue by Cat7373** [ST-DDT/CrazyLogin#10]
I use the bungee agent, the IP of all players in the database has become 127.0.0.1

Looks like the IP obtained through this code:
https://github.com/ST-DDT/CrazyLogin/blob/master/src/main/java/de/st_ddt/crazylogin/CrazyLogin.java#L1928

**Comment by Cat7373** [comment]
https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/

**Comment by ST-DDT** [comment]
Sorry but active development has stopped.

**Comment by ST-DDT** [comment]
You might be able to change the following config options to avoid issues with the same ips.

````yaml
# bypass forceSingleSession when using the same ip (true/false)
forceSingleSessionSameIPBypass: true
# maximum count of ips stored per player
maxStoredIPs: 5
# maximum players allowed to play on your server at once
maxOnlinesPerIP: 3
# maximum players allowed to register an account using the same ip on your server
maxRegistrationsPerIP: 3
# you have to login again after being inactive/offline for at least x seconds
# when using a new ip you are logged out automatically
autoLogout: 3600
````
