### ISSUE TITLE
Working with my plugin

### ISSUE THREAD

**Issue by GershonR** [ST-DDT/CrazyLogin#6]
Hi, I made a plugin that teleports you to a server then a world. The plugin works by using bukkit.teleport to move them to another world, the problem is when they login at that worlds spawn it teleports them back to another spawn. I'm pretty sure this is called by saveLogin, is there anyway to bypass this? Should I load the plugin as a dependency into my plugin and change the player location variable?

**Comment by ST-DDT** [comment]
You can disable this feature with `saveLoginEnabled: false`.

If you just want to use a different world then you could conifure this using:
````yml
saveLoginLocations:
  world:
    x: 24.0
    y: 64.0
    z: 256.0
    yaw: 0.0
    pitch: 0.0
    world: world
````
